services:
  - type: web
    name: codosphere
    # for a Vite build, tell Render this is a static site
    runtime: static
    # how to build your app
    buildCommand: npm install && npm run build
    # where Vite spits out the static assets
    staticPublishPath: dist
    # optionally control whether Render auto-deploys on git pushes
    autoDeploy: true

    # THIS is the magic: rewrite *every* incoming path back to index.html
    routes:
      - type: rewrite
        source: '/*'
        destination: /index.html
